"""document_ai/adapter.py — Provider-neutral DocumentAIAdapter interface.

The Processing Worker only calls DocumentAIAdapter.classify() and
DocumentAIAdapter.extract(). The concrete provider implementation
(Azure Document Intelligence, mock) is injected at runtime.

D13: Azure Document Intelligence is the production provider.
D18: ALL documents are sent for OCR regardless of physical_form_type.
     ADDITIONAL documents use prebuilt-read model.

Every provider adapter MUST normalise its confidence to 0-100.
A provider that cannot provide a documented deterministic normalisation
is not eligible for production configuration (DI_LLD_v2.2.md §3).
"""
from __future__ import annotations

import abc
from dataclasses import dataclass, field
from decimal import Decimal

from verigence.di.domain.enums import AICapability, FoundStatus


@dataclass(frozen=True)
class ClassificationCandidate:
    document_type_key: str
    confidence: Decimal          # 0-100, normalised by adapter
    method: str                  # e.g. "GOOGLE_DOCAI_CLASSIFIER"
    raw_provider_response: dict  # type: ignore[type-arg]  # kept for lineage


@dataclass(frozen=True)
class ExtractionField:
    """Schema for one field sent to the AI provider."""
    field_key: str
    aliases: list[str] = field(default_factory=list)
    instruction: str | None = None


@dataclass(frozen=True)
class FieldResult:
    """Result for one extracted field, returned by the AI provider."""
    field_key: str
    found_status: FoundStatus
    raw_value: str | None
    normalized_value: object | None     # post-normalization (set by rules layer)
    confidence: Decimal | None          # 0-100, normalised
    page_no: int | None
    evidence_region: dict | None        # type: ignore[type-arg]  # bounding box etc.
    provider_raw: dict                  # type: ignore[type-arg]  # full provider payload


@dataclass
class AIInvocationResult:
    """Envelope returned by classify() or extract()."""
    capability: AICapability
    adapter_key: str
    provider_request_id: str | None
    results: list[ClassificationCandidate] | list[FieldResult]
    usage_metrics: dict                 # type: ignore[type-arg]  # tokens, pages etc.
    error_code: str | None = None
    error_detail: str | None = None


class DocumentAIAdapter(abc.ABC):
    """Abstract provider-neutral AI adapter."""

    @property
    @abc.abstractmethod
    def adapter_key(self) -> str:
        """Stable identifier for this adapter (e.g. 'google_docai_v1')."""

    @abc.abstractmethod
    async def classify(
        self,
        artifact_bytes: bytes,
        mime_type: str,
        candidate_type_keys: list[str],
        hint: str | None = None,
        correlation_id: str | None = None,
    ) -> AIInvocationResult:
        """Classify a document. Returns ClassificationCandidate list."""

    @abc.abstractmethod
    async def extract(
        self,
        artifact_bytes: bytes,
        mime_type: str,
        fields: list[ExtractionField],
        correlation_id: str | None = None,
        physical_form_type: str = "PRINTABLE",   # D22 — routing hint for adapter
        document_type_key: str | None = None,    # D22 — schema registry lookup key
    ) -> AIInvocationResult:
        """Extract configured fields. Returns FieldResult list."""


class DocumentAIProviderError(RuntimeError):
    """Safe provider exception passed into the worker failure pipeline."""

    def __init__(
        self,
        *,
        technical_code: str,
        detail: str,
        retryable: bool,
        status_code: int | None = None,
    ) -> None:
        self.technical_code = technical_code
        self.retryable = retryable
        self.status_code = status_code
        # ``detail`` is generated by runtime_errors and therefore contains no
        # raw provider response or document/request value.
        super().__init__(detail)


class SafeDocumentAIAdapter(DocumentAIAdapter):
    """Boundary wrapper that prevents provider exception text crossing into DI.

    Successful provider behavior/results are delegated unchanged. Only exception
    representation is normalised to a stable technical code and safe description.
    """

    def __init__(self, delegate: DocumentAIAdapter) -> None:
        self._delegate = delegate

    @property
    def adapter_key(self) -> str:
        return self._delegate.adapter_key

    async def classify(
        self,
        artifact_bytes: bytes,
        mime_type: str,
        candidate_type_keys: list[str],
        hint: str | None = None,
        correlation_id: str | None = None,
    ) -> AIInvocationResult:
        try:
            return await self._delegate.classify(
                artifact_bytes=artifact_bytes,
                mime_type=mime_type,
                candidate_type_keys=candidate_type_keys,
                hint=hint,
                correlation_id=correlation_id,
            )
        except Exception as exc:  # noqa: BLE001
            raise _safe_provider_exception(exc, operation="classification_provider") from exc

    async def extract(
        self,
        artifact_bytes: bytes,
        mime_type: str,
        fields: list[ExtractionField],
        correlation_id: str | None = None,
        physical_form_type: str = "PRINTABLE",
        document_type_key: str | None = None,
    ) -> AIInvocationResult:
        try:
            return await self._delegate.extract(
                artifact_bytes=artifact_bytes,
                mime_type=mime_type,
                fields=fields,
                correlation_id=correlation_id,
                physical_form_type=physical_form_type,
                document_type_key=document_type_key,
            )
        except Exception as exc:  # noqa: BLE001
            raise _safe_provider_exception(exc, operation="extraction_provider") from exc


def _safe_provider_exception(exc: BaseException, *, operation: str) -> DocumentAIProviderError:
    from verigence.di.runtime_errors import technical_failure

    explicit_retryable = getattr(exc, "retryable", None)
    retryable = explicit_retryable if isinstance(explicit_retryable, bool) else None
    failure = technical_failure(exc, operation=operation, retryable=retryable)
    status_code = getattr(exc, "status_code", None)
    return DocumentAIProviderError(
        technical_code=failure.code,
        detail=failure.detail,
        retryable=failure.retryable,
        status_code=status_code if isinstance(status_code, int) else None,
    )


# ── Mock adapter — used locally and in CI ─────────────────────────────────────
class MockDocumentAIAdapter(DocumentAIAdapter):
    """Deterministic mock adapter for local development and CI.

    Returns high-confidence results so documents reach CONFIRMED state
    in the local Docker Compose environment without real API calls.
    """

    @property
    def adapter_key(self) -> str:
        return "mock_v1"

    async def classify(
        self,
        artifact_bytes: bytes,
        mime_type: str,
        candidate_type_keys: list[str],
        hint: str | None = None,
        correlation_id: str | None = None,
    ) -> AIInvocationResult:
        import uuid

        chosen = hint or (candidate_type_keys[0] if candidate_type_keys else "UNKNOWN")
        return AIInvocationResult(
            capability=AICapability.CLASSIFICATION,
            adapter_key=self.adapter_key,
            provider_request_id=str(uuid.uuid4()),
            results=[
                ClassificationCandidate(
                    document_type_key=chosen,
                    confidence=Decimal("95.00"),
                    method="MOCK",
                    raw_provider_response={},
                )
            ],
            usage_metrics={"pages": 1},
        )

    async def extract(
        self,
        artifact_bytes: bytes,
        mime_type: str,
        fields: list[ExtractionField],
        correlation_id: str | None = None,
        physical_form_type: str = "PRINTABLE",   # D22 — accepted, ignored by mock
        document_type_key: str | None = None,    # D22 — accepted, ignored by mock
    ) -> AIInvocationResult:
        import uuid

        results = [
            FieldResult(
                field_key=f.field_key,
                found_status=FoundStatus.FOUND,
                raw_value=f"mock_value_for_{f.field_key}",
                normalized_value=f"mock_value_for_{f.field_key}",
                confidence=Decimal("92.00"),
                page_no=1,
                evidence_region=None,
                provider_raw={},
            )
            for f in fields
        ]
        return AIInvocationResult(
            capability=AICapability.VISION_EXTRACTION,
            adapter_key=self.adapter_key,
            provider_request_id=str(uuid.uuid4()),
            results=results,
            usage_metrics={"pages": 1, "fields": len(fields)},
        )


def get_document_ai_adapter() -> DocumentAIAdapter:
    """FastAPI / worker dependency — returns configured adapter.

    DI_DOCAI_MOCK=true  → MockDocumentAIAdapter (local dev + CI)
    DI_DOCAI_MOCK=false → safe-wrapped GeminiDocumentAIAdapter (production — D19)
    """
    from verigence.di.settings import get_settings

    s = get_settings()
    if s.docai_mock:
        # Preserve the exact mock adapter type/behaviour used throughout tests.
        return MockDocumentAIAdapter()
    from verigence.di.document_ai.gemini_adapter import GeminiDocumentAIAdapter  # noqa: PLC0415

    return SafeDocumentAIAdapter(GeminiDocumentAIAdapter(api_key=s.docai_gemini_api_key))
