[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'uvicorn verigence.di.main:create_app --factory --host :: --port ${PORT:-8000} --timeout-graceful-shutdown 20 --max-requests 2000 --max-requests-jitter 200'"
healthcheckPath = "/health/live"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
