-- Verigence Standalone Document Intelligence
-- PostgreSQL Physical Schema Baseline v2.1
-- Vendor-neutral PostgreSQL. No cloud-provider-specific extension or datatype is required.
-- UUID values are generated by the application.

BEGIN;

CREATE SCHEMA IF NOT EXISTS docintel;

-- -----------------------------------------------------------------------------
-- Tenant context helper for Row-Level Security
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION docintel.current_tenant_id()
RETURNS text
LANGUAGE sql
STABLE
AS $$
    SELECT NULLIF(current_setting('app.tenant_id', true), '')
$$;

-- -----------------------------------------------------------------------------
-- Tenant runtime settings / actors / registered devices
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.tenant_settings (
    tenant_id                       varchar(128) PRIMARY KEY,
    tenant_storage_key              uuid NOT NULL UNIQUE,
    timezone_name                   varchar(100) NOT NULL,
    eod_retry_local_time            time NOT NULL,
    eod_retry_enabled               boolean NOT NULL DEFAULT true,
    classification_acceptance_score numeric(5,2) NOT NULL
                                      CHECK (classification_acceptance_score >= 0 AND classification_acceptance_score <= 100),
    subject_matching_min_confidence numeric(5,2) NOT NULL
                                      CHECK (subject_matching_min_confidence >= 0 AND subject_matching_min_confidence <= 100),
    upload_timeout_minutes          integer NOT NULL CHECK (upload_timeout_minutes > 0),
    max_upload_bytes                bigint NOT NULL CHECK (max_upload_bytes > 0),
    allowed_mime_types              jsonb NOT NULL
                                      CHECK (jsonb_typeof(allowed_mime_types) = 'array' AND jsonb_array_length(allowed_mime_types) > 0),
    quality_policy                  jsonb NOT NULL
                                      CHECK (jsonb_typeof(quality_policy) = 'array' AND jsonb_array_length(quality_policy) > 0),
    whatsapp_subject_reference_prefix varchar(80) NOT NULL,
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED')),
    created_at_utc                  timestamptz NOT NULL,
    updated_at_utc                  timestamptz NOT NULL
);

CREATE TABLE docintel.actors (
    tenant_id                       varchar(128) NOT NULL,
    actor_id                        varchar(160) NOT NULL,
    actor_type                      varchar(20) NOT NULL
                                      CHECK (actor_type IN ('USER','SYSTEM','SERVICE')),
    display_name                    varchar(240),
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','DISABLED')),
    created_at_utc                  timestamptz NOT NULL,
    updated_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, actor_id),
    UNIQUE (tenant_id, actor_id, actor_type),
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id)
);

CREATE TABLE docintel.registered_devices (
    tenant_id                       varchar(128) NOT NULL,
    device_id                       varchar(200) NOT NULL,
    actor_id                        varchar(160) NOT NULL,
    device_label                    varchar(240),
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','REVOKED')),
    registered_at_utc               timestamptz NOT NULL,
    revoked_at_utc                  timestamptz,
    PRIMARY KEY (tenant_id, device_id),
    FOREIGN KEY (tenant_id, actor_id) REFERENCES docintel.actors(tenant_id, actor_id)
);

-- -----------------------------------------------------------------------------
-- Lightweight standalone Subject Registry
-- Verigence owns Subject identity; this is not a CRM/customer master.
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.subjects (
    tenant_id                       varchar(128) NOT NULL,
    subject_id                      uuid NOT NULL,
    subject_type                    varchar(20) NOT NULL
                                      CHECK (subject_type IN ('PERSON','ORGANIZATION','OTHER')),
    display_name                    varchar(240),
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','INACTIVE')),
    created_by_actor_id             varchar(160) NOT NULL,
    created_at_utc                  timestamptz NOT NULL,
    updated_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, subject_id),
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id),
    FOREIGN KEY (tenant_id, created_by_actor_id) REFERENCES docintel.actors(tenant_id, actor_id)
);

CREATE INDEX ix_subjects_search
ON docintel.subjects(tenant_id, status, display_name);

-- -----------------------------------------------------------------------------
-- Retention
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.retention_policies (
    tenant_id                       varchar(128) NOT NULL,
    retention_policy_id             uuid NOT NULL,
    policy_key                      varchar(120) NOT NULL,
    display_name                    varchar(240) NOT NULL,
    retention_days                  integer NOT NULL CHECK (retention_days >= 0),
    disposition                     varchar(30) NOT NULL
                                      CHECK (disposition IN ('PURGE_CONTENT','KEEP_CONTENT')),
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at_utc                  timestamptz NOT NULL,
    updated_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, retention_policy_id),
    UNIQUE (tenant_id, policy_key),
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id)
);

ALTER TABLE docintel.tenant_settings
ADD COLUMN active_retention_policy_id uuid;

ALTER TABLE docintel.tenant_settings
ADD CONSTRAINT fk_tenant_active_retention
FOREIGN KEY (tenant_id, active_retention_policy_id)
REFERENCES docintel.retention_policies(tenant_id, retention_policy_id);

-- -----------------------------------------------------------------------------
-- Document Type / canonical fields / rule catalogs
-- owner_tenant_id NULL means global/default configuration.
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.document_types (
    document_type_id                uuid PRIMARY KEY,
    owner_tenant_id                 varchar(128),
    document_type_key               varchar(120) NOT NULL,
    display_name                    varchar(240) NOT NULL,
    description                     text,
    category                        varchar(100),
    status                          varchar(20) NOT NULL DEFAULT 'DRAFT'
                                      CHECK (status IN ('DRAFT','ACTIVE','RETIRED')),
    created_at_utc                  timestamptz NOT NULL,
    updated_at_utc                  timestamptz NOT NULL,
    FOREIGN KEY (owner_tenant_id) REFERENCES docintel.tenant_settings(tenant_id)
);

CREATE UNIQUE INDEX uq_document_type_scope_key
ON docintel.document_types(COALESCE(owner_tenant_id, '__GLOBAL__'), document_type_key);

CREATE TABLE docintel.canonical_fields (
    canonical_field_id              uuid PRIMARY KEY,
    owner_tenant_id                 varchar(128),
    field_key                       varchar(160) NOT NULL,
    display_name                    varchar(240) NOT NULL,
    data_type                       varchar(30) NOT NULL
                                      CHECK (data_type IN ('STRING','INTEGER','DECIMAL','BOOLEAN','DATE','DATETIME','CURRENCY','IDENTIFIER','PHONE','EMAIL','JSON')),
    description                     text,
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','RETIRED')),
    created_at_utc                  timestamptz NOT NULL,
    updated_at_utc                  timestamptz NOT NULL,
    FOREIGN KEY (owner_tenant_id) REFERENCES docintel.tenant_settings(tenant_id)
);

CREATE UNIQUE INDEX uq_canonical_field_scope_key
ON docintel.canonical_fields(COALESCE(owner_tenant_id, '__GLOBAL__'), field_key);

CREATE TABLE docintel.normalization_rule_catalog (
    rule_key                        varchar(120) PRIMARY KEY,
    description                     text NOT NULL,
    implementation_key              varchar(160) NOT NULL,
    parameter_schema                jsonb,
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','RETIRED'))
);

CREATE TABLE docintel.validation_rule_catalog (
    rule_key                        varchar(120) PRIMARY KEY,
    description                     text NOT NULL,
    implementation_key              varchar(160) NOT NULL,
    parameter_schema                jsonb,
    result_scope                    varchar(30) NOT NULL DEFAULT 'FIELD'
                                      CHECK (result_scope IN ('FIELD','DOCUMENT','CROSS_FIELD')),
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','RETIRED'))
);

CREATE TABLE docintel.quality_rule_catalog (
    rule_key                        varchar(120) PRIMARY KEY,
    description                     text NOT NULL,
    implementation_key              varchar(160) NOT NULL,
    parameter_schema                jsonb,
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','RETIRED'))
);

-- -----------------------------------------------------------------------------
-- Extraction Profiles: DB-driven, versioned, immutable once published
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.extraction_profiles (
    profile_id                      uuid PRIMARY KEY,
    document_type_id                uuid NOT NULL,
    scope_tenant_id                 varchar(128),
    version_no                      integer NOT NULL CHECK (version_no > 0),
    profile_name                    varchar(240) NOT NULL,
    status                          varchar(20) NOT NULL
                                      CHECK (status IN ('DRAFT','PUBLISHED','RETIRED')),
    classification_hint             text,
    created_by_actor_id             varchar(160) NOT NULL,
    published_by_actor_id           varchar(160),
    created_at_utc                  timestamptz NOT NULL,
    published_at_utc                timestamptz,
    updated_at_utc                  timestamptz NOT NULL,
    FOREIGN KEY (document_type_id) REFERENCES docintel.document_types(document_type_id),
    FOREIGN KEY (scope_tenant_id) REFERENCES docintel.tenant_settings(tenant_id),
    CHECK ((status = 'DRAFT' AND published_by_actor_id IS NULL AND published_at_utc IS NULL)
        OR (status IN ('PUBLISHED','RETIRED') AND published_by_actor_id IS NOT NULL AND published_at_utc IS NOT NULL))
);

CREATE UNIQUE INDEX uq_extraction_profile_version
ON docintel.extraction_profiles(
    document_type_id,
    COALESCE(scope_tenant_id, '__GLOBAL__'),
    version_no
);

CREATE UNIQUE INDEX uq_extraction_profile_published
ON docintel.extraction_profiles(
    document_type_id,
    COALESCE(scope_tenant_id, '__GLOBAL__')
)
WHERE status = 'PUBLISHED';

CREATE TABLE docintel.extraction_profile_fields (
    profile_field_id                uuid PRIMARY KEY,
    profile_id                      uuid NOT NULL,
    canonical_field_id              uuid NOT NULL,
    enabled                         boolean NOT NULL DEFAULT true,
    expected                        boolean NOT NULL DEFAULT true,
    extraction_instruction          text,
    aliases                         jsonb,
    score_included                  boolean NOT NULL DEFAULT true,
    score_weight                    numeric(10,4) NOT NULL DEFAULT 1.0 CHECK (score_weight >= 0),
    use_for_subject_matching        boolean NOT NULL DEFAULT false,
    subject_identifier_type         varchar(80),
    manual_correction_allowed       boolean NOT NULL DEFAULT true,
    display_sequence                integer NOT NULL DEFAULT 100,
    created_at_utc                  timestamptz NOT NULL,
    updated_at_utc                  timestamptz NOT NULL,
    UNIQUE (profile_id, canonical_field_id),
    FOREIGN KEY (profile_id) REFERENCES docintel.extraction_profiles(profile_id),
    FOREIGN KEY (canonical_field_id) REFERENCES docintel.canonical_fields(canonical_field_id)
);

-- Configuration publication invariant:
-- The service must reject publication unless at least one enabled, expected,
-- score_included field has score_weight > 0. This guarantees a non-zero scoring denominator. This is a cross-row invariant and is enforced
-- transactionally by the configuration service.
CREATE TABLE docintel.profile_field_normalizers (
    profile_field_normalizer_id     uuid PRIMARY KEY,
    profile_field_id                uuid NOT NULL,
    sequence_no                     integer NOT NULL CHECK (sequence_no > 0),
    rule_key                        varchar(120) NOT NULL,
    parameters                      jsonb,
    UNIQUE (profile_field_id, sequence_no),
    FOREIGN KEY (profile_field_id) REFERENCES docintel.extraction_profile_fields(profile_field_id),
    FOREIGN KEY (rule_key) REFERENCES docintel.normalization_rule_catalog(rule_key)
);

CREATE TABLE docintel.profile_field_validators (
    profile_field_validator_id      uuid PRIMARY KEY,
    profile_field_id                uuid NOT NULL,
    sequence_no                     integer NOT NULL CHECK (sequence_no > 0),
    rule_key                        varchar(120) NOT NULL,
    parameters                      jsonb,
    severity                        varchar(20) NOT NULL DEFAULT 'ERROR'
                                      CHECK (severity IN ('INFO','WARNING','ERROR')),
    UNIQUE (profile_field_id, sequence_no),
    FOREIGN KEY (profile_field_id) REFERENCES docintel.extraction_profile_fields(profile_field_id),
    FOREIGN KEY (rule_key) REFERENCES docintel.validation_rule_catalog(rule_key)
);

-- -----------------------------------------------------------------------------
-- Required/Optional Document Profiles
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.document_requirement_profiles (
    tenant_id                       varchar(128) NOT NULL,
    requirement_profile_id          uuid NOT NULL,
    profile_key                     varchar(120) NOT NULL,
    version_no                      integer NOT NULL CHECK (version_no > 0),
    description                     text,
    status                          varchar(20) NOT NULL
                                      CHECK (status IN ('DRAFT','PUBLISHED','RETIRED')),
    created_by_actor_id             varchar(160) NOT NULL,
    published_by_actor_id           varchar(160),
    created_at_utc                  timestamptz NOT NULL,
    published_at_utc                timestamptz,
    updated_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, requirement_profile_id),
    UNIQUE (tenant_id, profile_key, version_no),
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id),
    FOREIGN KEY (tenant_id, created_by_actor_id) REFERENCES docintel.actors(tenant_id, actor_id),
    FOREIGN KEY (tenant_id, published_by_actor_id) REFERENCES docintel.actors(tenant_id, actor_id),
    CHECK ((status = 'DRAFT' AND published_by_actor_id IS NULL AND published_at_utc IS NULL)
        OR (status IN ('PUBLISHED','RETIRED') AND published_by_actor_id IS NOT NULL AND published_at_utc IS NOT NULL))
);

CREATE UNIQUE INDEX uq_requirement_profile_published
ON docintel.document_requirement_profiles(tenant_id, profile_key)
WHERE status = 'PUBLISHED';

CREATE TABLE docintel.document_requirement_profile_items (
    tenant_id                       varchar(128) NOT NULL,
    requirement_item_id             uuid NOT NULL,
    requirement_profile_id          uuid NOT NULL,
    document_type_id                uuid NOT NULL,
    requirement_classification      varchar(20) NOT NULL
                                      CHECK (requirement_classification IN ('MANDATORY','OPTIONAL')),
    minimum_count                   integer NOT NULL DEFAULT 1 CHECK (minimum_count > 0),
    display_sequence                integer NOT NULL DEFAULT 100,
    enabled                         boolean NOT NULL DEFAULT true,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, requirement_item_id),
    UNIQUE (tenant_id, requirement_profile_id, document_type_id),
    FOREIGN KEY (tenant_id, requirement_profile_id)
      REFERENCES docintel.document_requirement_profiles(tenant_id, requirement_profile_id),
    FOREIGN KEY (document_type_id) REFERENCES docintel.document_types(document_type_id)
);

CREATE TABLE docintel.subject_requirement_assignments (
    tenant_id                       varchar(128) NOT NULL,
    subject_id                      uuid NOT NULL,
    requirement_profile_id          uuid NOT NULL,
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','REPLACED')),
    assigned_by_actor_id            varchar(160) NOT NULL,
    assigned_at_utc                 timestamptz NOT NULL,
    replaced_at_utc                 timestamptz,
    PRIMARY KEY (tenant_id, subject_id, requirement_profile_id),
    FOREIGN KEY (tenant_id, requirement_profile_id)
      REFERENCES docintel.document_requirement_profiles(tenant_id, requirement_profile_id),
    FOREIGN KEY (tenant_id, subject_id) REFERENCES docintel.subjects(tenant_id, subject_id),
    FOREIGN KEY (tenant_id, assigned_by_actor_id) REFERENCES docintel.actors(tenant_id, actor_id)
);

CREATE UNIQUE INDEX uq_subject_active_requirement_assignment
ON docintel.subject_requirement_assignments(tenant_id, subject_id)
WHERE status = 'ACTIVE';

CREATE OR REPLACE FUNCTION docintel.require_published_requirement_on_assignment()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    p_status varchar(20);
BEGIN
    IF NEW.status = 'ACTIVE' THEN
        SELECT status INTO p_status
        FROM docintel.document_requirement_profiles
        WHERE tenant_id = NEW.tenant_id
          AND requirement_profile_id = NEW.requirement_profile_id;
        IF p_status IS DISTINCT FROM 'PUBLISHED' THEN
            RAISE EXCEPTION 'active Subject assignment must reference a currently PUBLISHED Requirement Profile';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER subject_requirement_assignment_guard
BEFORE INSERT OR UPDATE OF requirement_profile_id, status ON docintel.subject_requirement_assignments
FOR EACH ROW EXECUTE FUNCTION docintel.require_published_requirement_on_assignment();


-- -----------------------------------------------------------------------------
-- Subject identifiers and channel identities for deterministic WhatsApp matching
-- Verigence owns a lightweight Subject Registry; this is not a CRM/customer master.
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.subject_identifiers (
    tenant_id                       varchar(128) NOT NULL,
    subject_identifier_id           uuid NOT NULL,
    subject_id                      uuid NOT NULL,
    identifier_type                 varchar(80) NOT NULL,
    normalized_value                text NOT NULL,
    normalized_value_hash           char(64),
    verification_status             varchar(20) NOT NULL DEFAULT 'VERIFIED'
                                      CHECK (verification_status IN ('VERIFIED','UNVERIFIED')),
    source                          varchar(30) NOT NULL
                                      CHECK (source IN ('EXTERNAL','DOCUMENT','MANUAL')),
    valid_from_utc                  timestamptz NOT NULL,
    valid_to_utc                    timestamptz,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, subject_identifier_id),
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id),
    FOREIGN KEY (tenant_id, subject_id) REFERENCES docintel.subjects(tenant_id, subject_id)
);

CREATE INDEX ix_subject_identifier_exact
ON docintel.subject_identifiers(tenant_id, identifier_type, normalized_value)
WHERE valid_to_utc IS NULL AND verification_status = 'VERIFIED';

CREATE TABLE docintel.channel_identities (
    tenant_id                       varchar(128) NOT NULL,
    channel_identity_id             uuid NOT NULL,
    channel                         varchar(30) NOT NULL,
    external_identity_type          varchar(80) NOT NULL,
    external_identity_value         varchar(500) NOT NULL,
    mapped_subject_id               uuid,
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','INACTIVE')),
    valid_from_utc                  timestamptz NOT NULL,
    valid_to_utc                    timestamptz,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, channel_identity_id),
    UNIQUE (tenant_id, channel, external_identity_type, external_identity_value),
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id),
    FOREIGN KEY (tenant_id, mapped_subject_id) REFERENCES docintel.subjects(tenant_id, subject_id)
);

-- -----------------------------------------------------------------------------
-- Documents
-- Requirement classification is intentionally derived at enquiry time from
-- active Requirement Profile tables, not stored as authoritative Document state.
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.documents (
    tenant_id                       varchar(128) NOT NULL,
    document_id                     uuid NOT NULL,
    subject_id                      uuid,
    document_type_id                uuid,
    active_retention_policy_id      uuid NOT NULL,
    retention_until_utc             timestamptz,
    retention_disposition           varchar(30) NOT NULL
                                      CHECK (retention_disposition IN ('PURGE_CONTENT','KEEP_CONTENT')),
    source_channel                  varchar(20) NOT NULL
                                      CHECK (source_channel IN ('MOBILE','WEB','API','WHATSAPP')),
    uploaded_by_actor_type          varchar(20) NOT NULL
                                      CHECK (uploaded_by_actor_type IN ('USER','SYSTEM','SERVICE')),
    uploaded_by_actor_id            varchar(160) NOT NULL,
    source_device_id                varchar(200),
    captured_at                     timestamptz,
    source_event_at                 timestamptz,
    registered_at_utc               timestamptz NOT NULL,
    correlation_id                  varchar(128) NOT NULL,
    processed_at_utc                timestamptz,
    confirmed_at_utc                timestamptz,
    original_filename               varchar(500),
    declared_mime_type              varchar(160),
    detected_mime_type              varchar(160),
    file_size_bytes                 bigint CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    content_hash_sha256             char(64),
    page_count                      integer CHECK (page_count IS NULL OR page_count >= 1),
    source_reference                varchar(500),
    duplicate_of_document_id        uuid,
    upload_status                   varchar(20) NOT NULL DEFAULT 'RECEIVING'
                                      CHECK (upload_status IN ('RECEIVING','VALIDATING','FIT','NOT_FIT','CORRUPT','UPLOAD_FAILED')),
    upload_issue_code               varchar(120),
    upload_issue_detail             text,
    processing_status               varchar(20) NOT NULL DEFAULT 'NOT_STARTED'
                                      CHECK (processing_status IN ('NOT_STARTED','PROCESSING','RETRY_PENDING','PROCESSED','FAILED')),
    processing_failure_code         varchar(120),
    processing_failure_detail       text,
    confirmation_status             varchar(20) NOT NULL DEFAULT 'PENDING'
                                      CHECK (confirmation_status IN ('PENDING','CONFIRMED','NOT_CONFIRMED')),
    confidence_score                numeric(5,2)
                                      CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)),
    verification_threshold_applied  numeric(5,2)
                                      CHECK (verification_threshold_applied IS NULL OR verification_threshold_applied = 90.00),
    human_verification_status  varchar(20)
                                      CHECK (human_verification_status IS NULL OR human_verification_status IN ('MANDATORY','OPTIONAL')),
    verification_state       varchar(20) NOT NULL DEFAULT 'NOT_VERIFIED'
                                      CHECK (verification_state IN ('NOT_VERIFIED','VERIFIED')),
    current_processing_run_id       uuid,
    replaces_document_id            uuid,
    replaced_by_document_id         uuid,
    content_state                   varchar(20) NOT NULL DEFAULT 'AVAILABLE'
                                      CHECK (content_state IN ('AVAILABLE','PURGED')),
    created_at_utc                  timestamptz NOT NULL,
    updated_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, document_id),
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id),
    FOREIGN KEY (tenant_id, subject_id) REFERENCES docintel.subjects(tenant_id, subject_id),
    FOREIGN KEY (document_type_id) REFERENCES docintel.document_types(document_type_id),
    FOREIGN KEY (tenant_id, active_retention_policy_id)
      REFERENCES docintel.retention_policies(tenant_id, retention_policy_id),
    FOREIGN KEY (tenant_id, uploaded_by_actor_id, uploaded_by_actor_type)
      REFERENCES docintel.actors(tenant_id, actor_id, actor_type),
    FOREIGN KEY (tenant_id, duplicate_of_document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (tenant_id, replaces_document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (tenant_id, replaced_by_document_id) REFERENCES docintel.documents(tenant_id, document_id)
);


-- Machine-state invariants.
ALTER TABLE docintel.documents
ADD CONSTRAINT ck_documents_bad_upload_not_processed
CHECK (
    upload_status NOT IN ('NOT_FIT','CORRUPT','UPLOAD_FAILED')
    OR (
        processing_status = 'NOT_STARTED'
        AND confirmation_status = 'PENDING'
        AND confidence_score IS NULL
        AND verification_threshold_applied IS NULL
        AND human_verification_status IS NULL
        AND verification_state = 'NOT_VERIFIED'
    )
);

ALTER TABLE docintel.documents
ADD CONSTRAINT ck_documents_confirmation_invariants
CHECK (
    (
        confirmation_status = 'CONFIRMED'
        AND upload_status = 'FIT'
        AND processing_status = 'PROCESSED'
        AND confidence_score IS NOT NULL
        AND verification_threshold_applied IS NOT NULL
        AND human_verification_status IS NOT NULL
        AND human_verification_status =
            CASE WHEN confidence_score > verification_threshold_applied
                 THEN 'OPTIONAL' ELSE 'MANDATORY' END
    )
    OR (
        confirmation_status = 'NOT_CONFIRMED'
        AND upload_status = 'FIT'
        AND processing_status = 'FAILED'
        AND confidence_score IS NULL
        AND verification_threshold_applied IS NULL
        AND human_verification_status IS NULL
        AND verification_state = 'NOT_VERIFIED'
    )
    OR (
        confirmation_status = 'PENDING'
        AND processing_status IN ('NOT_STARTED','PROCESSING','RETRY_PENDING')
        AND confidence_score IS NULL
        AND verification_threshold_applied IS NULL
        AND human_verification_status IS NULL
        AND verification_state = 'NOT_VERIFIED'
    )
);

ALTER TABLE docintel.documents
ADD CONSTRAINT ck_documents_verified_only_after_confirmation
CHECK (
    verification_state <> 'VERIFIED'
    OR confirmation_status = 'CONFIRMED'
);

CREATE INDEX ix_documents_subject_type_time
ON docintel.documents(tenant_id, subject_id, document_type_id, registered_at_utc DESC);

CREATE INDEX ix_documents_subject_status
ON docintel.documents(tenant_id, subject_id, upload_status, processing_status, confirmation_status);

CREATE INDEX ix_documents_uploader_quality
ON docintel.documents(tenant_id, uploaded_by_actor_id, registered_at_utc DESC, upload_status);

CREATE INDEX ix_documents_verification_queue
ON docintel.documents(tenant_id, human_verification_status, verification_state, registered_at_utc DESC)
WHERE confirmation_status = 'CONFIRMED';

CREATE INDEX ix_documents_hash
ON docintel.documents(tenant_id, content_hash_sha256, file_size_bytes)
WHERE content_hash_sha256 IS NOT NULL;

-- -----------------------------------------------------------------------------
-- Storage artifacts
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.document_artifacts (
    tenant_id                       varchar(128) NOT NULL,
    artifact_id                     uuid NOT NULL,
    document_id                     uuid NOT NULL,
    processing_run_id               uuid,
    storage_id                      uuid NOT NULL,
    logical_object_key              varchar(1000) NOT NULL,
    artifact_type                   varchar(30) NOT NULL
                                      CHECK (artifact_type IN ('ORIGINAL','NORMALIZED','PREVIEW','PAGE_IMAGE','OCR_RAW','PROVIDER_RAW','OTHER')),
    page_no                         integer,
    mime_type                       varchar(160),
    file_size_bytes                 bigint CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    content_hash_sha256             char(64),
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, artifact_id),
    UNIQUE (tenant_id, storage_id),
    UNIQUE (tenant_id, logical_object_key),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id)
);

-- -----------------------------------------------------------------------------
-- Deterministic upload-quality rule results
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.document_quality_results (
    tenant_id                       varchar(128) NOT NULL,
    quality_result_id               uuid NOT NULL,
    document_id                     uuid NOT NULL,
    rule_key                        varchar(120) NOT NULL,
    outcome                         varchar(20) NOT NULL
                                      CHECK (outcome IN ('PASS','FAIL','SKIP','ERROR')),
    parameters_applied              jsonb,
    measurement                     jsonb,
    message                         text,
    evaluated_at_utc                timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, quality_result_id),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (rule_key) REFERENCES docintel.quality_rule_catalog(rule_key)
);

CREATE INDEX ix_document_quality_results_document
ON docintel.document_quality_results(tenant_id, document_id, evaluated_at_utc);

-- -----------------------------------------------------------------------------
-- Internal PostgreSQL processing jobs and immutable processing runs
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.processing_jobs (
    tenant_id                       varchar(128) NOT NULL,
    processing_job_id               uuid NOT NULL,
    document_id                     uuid NOT NULL,
    correlation_id                  varchar(128) NOT NULL,
    job_type                        varchar(20) NOT NULL
                                      CHECK (job_type IN ('INITIAL','EOD_RETRY')),
    job_status                      varchar(20) NOT NULL DEFAULT 'PENDING'
                                      CHECK (job_status IN ('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED')),
    due_at_utc                      timestamptz NOT NULL,
    attempt_no                      integer NOT NULL CHECK (attempt_no IN (1,2)),
    locked_by                       varchar(160),
    locked_at_utc                   timestamptz,
    started_at_utc                  timestamptz,
    completed_at_utc                timestamptz,
    error_code                      varchar(120),
    error_detail                    text,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, processing_job_id),
    UNIQUE (tenant_id, document_id, job_type),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id)
);

ALTER TABLE docintel.processing_jobs
ADD CONSTRAINT ck_processing_job_attempt_type
CHECK (
    (job_type = 'INITIAL' AND attempt_no = 1)
    OR (job_type = 'EOD_RETRY' AND attempt_no = 2)
);

CREATE INDEX ix_processing_jobs_claim
ON docintel.processing_jobs(tenant_id, job_status, due_at_utc)
WHERE job_status = 'PENDING';

CREATE TABLE docintel.processing_runs (
    tenant_id                       varchar(128) NOT NULL,
    processing_run_id               uuid NOT NULL,
    processing_job_id               uuid NOT NULL,
    document_id                     uuid NOT NULL,
    correlation_id                  varchar(128) NOT NULL,
    extraction_profile_id           uuid,
    run_type                        varchar(20) NOT NULL
                                      CHECK (run_type IN ('INITIAL','EOD_RETRY')),
    run_status                      varchar(20) NOT NULL
                                      CHECK (run_status IN ('RUNNING','COMPLETED','FAILED')),
    error_class                     varchar(20)
                                      CHECK (error_class IS NULL OR error_class IN ('RETRYABLE','NON_RETRYABLE')),
    error_code                      varchar(120),
    error_detail                    text,
    pipeline_version                varchar(80) NOT NULL,
    started_at_utc                  timestamptz NOT NULL,
    completed_at_utc                timestamptz,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, processing_run_id),
    UNIQUE (tenant_id, document_id, processing_run_id),
    FOREIGN KEY (tenant_id, processing_job_id) REFERENCES docintel.processing_jobs(tenant_id, processing_job_id),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (extraction_profile_id) REFERENCES docintel.extraction_profiles(profile_id)
);

ALTER TABLE docintel.documents
ADD CONSTRAINT fk_documents_current_processing_run
FOREIGN KEY (tenant_id, document_id, current_processing_run_id)
REFERENCES docintel.processing_runs(tenant_id, document_id, processing_run_id);

ALTER TABLE docintel.document_artifacts
ADD CONSTRAINT fk_artifact_processing_run
FOREIGN KEY (tenant_id, document_id, processing_run_id)
REFERENCES docintel.processing_runs(tenant_id, document_id, processing_run_id);

CREATE TABLE docintel.processor_invocations (
    tenant_id                       varchar(128) NOT NULL,
    invocation_id                   uuid NOT NULL,
    processing_run_id               uuid NOT NULL,
    correlation_id                  varchar(128) NOT NULL,
    capability                      varchar(30) NOT NULL
                                      CHECK (capability IN ('CLASSIFICATION','OCR','VISION_EXTRACTION','OTHER')),
    adapter_key                     varchar(120) NOT NULL,
    engine_key                      varchar(200),
    outcome                         varchar(20) NOT NULL
                                      CHECK (outcome IN ('STARTED','SUCCESS','FAILED','TIMEOUT','SKIPPED')),
    provider_request_id             varchar(300),
    usage_metrics                   jsonb,
    error_code                      varchar(120),
    error_detail                    text,
    started_at_utc                  timestamptz NOT NULL,
    completed_at_utc                timestamptz,
    PRIMARY KEY (tenant_id, invocation_id),
    FOREIGN KEY (tenant_id, processing_run_id) REFERENCES docintel.processing_runs(tenant_id, processing_run_id)
);

-- -----------------------------------------------------------------------------
-- Classification / extracted facts / accepted values / validation
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.document_classifications (
    tenant_id                       varchar(128) NOT NULL,
    classification_id               uuid NOT NULL,
    processing_run_id               uuid NOT NULL,
    document_id                     uuid NOT NULL,
    document_type_id                uuid,
    document_type_key_observed      varchar(120),
    confidence_score                numeric(5,2)
                                      CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)),
    classification_method           varchar(60) NOT NULL,
    accepted                        boolean NOT NULL DEFAULT false,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, classification_id),
    FOREIGN KEY (tenant_id, processing_run_id) REFERENCES docintel.processing_runs(tenant_id, processing_run_id),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (document_type_id) REFERENCES docintel.document_types(document_type_id)
);

CREATE TABLE docintel.extracted_facts (
    tenant_id                       varchar(128) NOT NULL,
    extracted_fact_id               uuid NOT NULL,
    processing_run_id               uuid NOT NULL,
    document_id                     uuid NOT NULL,
    profile_field_id                uuid NOT NULL,
    canonical_field_id              uuid NOT NULL,
    found_status                    varchar(20) NOT NULL
                                      CHECK (found_status IN ('FOUND','NOT_FOUND','AMBIGUOUS','ERROR')),
    raw_value_text                  text,
    normalized_value                jsonb,
    confidence_score                numeric(5,2)
                                      CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)),
    page_no                         integer,
    evidence_region                 jsonb,
    invocation_id                   uuid,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, extracted_fact_id),
    UNIQUE (tenant_id, document_id, extracted_fact_id),
    FOREIGN KEY (tenant_id, processing_run_id) REFERENCES docintel.processing_runs(tenant_id, processing_run_id),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (profile_field_id) REFERENCES docintel.extraction_profile_fields(profile_field_id),
    FOREIGN KEY (canonical_field_id) REFERENCES docintel.canonical_fields(canonical_field_id),
    FOREIGN KEY (tenant_id, invocation_id) REFERENCES docintel.processor_invocations(tenant_id, invocation_id)
);

CREATE INDEX ix_extracted_facts_doc_field
ON docintel.extracted_facts(tenant_id, document_id, canonical_field_id, created_at_utc DESC);

CREATE TABLE docintel.document_field_values (
    tenant_id                       varchar(128) NOT NULL,
    document_field_value_id         uuid NOT NULL,
    document_id                     uuid NOT NULL,
    canonical_field_id              uuid NOT NULL,
    current_value                   jsonb,
    value_source                    varchar(20) NOT NULL
                                      CHECK (value_source IN ('MACHINE','HUMAN','EXTERNAL')),
    source_extracted_fact_id        uuid,
    source_verification_id          uuid,
    confidence_score                numeric(5,2)
                                      CHECK (confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)),
    accepted_by_actor_id            varchar(160) NOT NULL,
    accepted_at_utc                 timestamptz NOT NULL,
    version_no                      integer NOT NULL CHECK (version_no > 0),
    is_current                      boolean NOT NULL DEFAULT true,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, document_field_value_id),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (canonical_field_id) REFERENCES docintel.canonical_fields(canonical_field_id),
    FOREIGN KEY (tenant_id, document_id, source_extracted_fact_id) REFERENCES docintel.extracted_facts(tenant_id, document_id, extracted_fact_id),
    FOREIGN KEY (tenant_id, accepted_by_actor_id) REFERENCES docintel.actors(tenant_id, actor_id)
);

CREATE UNIQUE INDEX uq_document_current_field_value
ON docintel.document_field_values(tenant_id, document_id, canonical_field_id)
WHERE is_current = true;

CREATE TABLE docintel.validation_results (
    tenant_id                       varchar(128) NOT NULL,
    validation_result_id            uuid NOT NULL,
    processing_run_id               uuid NOT NULL,
    document_id                     uuid NOT NULL,
    canonical_field_id              uuid,
    rule_key                        varchar(120) NOT NULL,
    result                          varchar(20) NOT NULL
                                      CHECK (result IN ('PASS','FAIL','WARNING','SKIP','ERROR')),
    severity                        varchar(20) NOT NULL
                                      CHECK (severity IN ('INFO','WARNING','ERROR')),
    message                         text,
    details                         jsonb,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, validation_result_id),
    FOREIGN KEY (tenant_id, processing_run_id) REFERENCES docintel.processing_runs(tenant_id, processing_run_id),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (canonical_field_id) REFERENCES docintel.canonical_fields(canonical_field_id),
    FOREIGN KEY (rule_key) REFERENCES docintel.validation_rule_catalog(rule_key)
);

-- -----------------------------------------------------------------------------
-- Human verification
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.human_verifications (
    tenant_id                       varchar(128) NOT NULL,
    verification_id                 uuid NOT NULL,
    subject_id_at_time              uuid,
    document_id                     uuid NOT NULL,
    human_verification_status_at_time varchar(20) NOT NULL
                                      CHECK (human_verification_status_at_time IN ('MANDATORY','OPTIONAL')),
    machine_confidence_score        numeric(5,2) NOT NULL
                                      CHECK (machine_confidence_score >= 0 AND machine_confidence_score <= 100),
    verification_outcome            varchar(20) NOT NULL DEFAULT 'VERIFIED'
                                      CHECK (verification_outcome = 'VERIFIED'),
    verified_by_actor_id            varchar(160) NOT NULL,
    remarks                         text,
    verified_at_utc                 timestamptz NOT NULL,
    created_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, verification_id),
    UNIQUE (tenant_id, document_id),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (tenant_id, subject_id_at_time) REFERENCES docintel.subjects(tenant_id, subject_id),
    FOREIGN KEY (tenant_id, verified_by_actor_id) REFERENCES docintel.actors(tenant_id, actor_id)
);

CREATE INDEX ix_human_verification_document
ON docintel.human_verifications(tenant_id, document_id, verified_at_utc DESC);

ALTER TABLE docintel.document_field_values
ADD CONSTRAINT fk_document_field_value_verification
FOREIGN KEY (tenant_id, source_verification_id)
REFERENCES docintel.human_verifications(tenant_id, verification_id);

ALTER TABLE docintel.document_field_values
ADD CONSTRAINT ck_document_field_value_lineage
CHECK (
    (value_source = 'MACHINE' AND source_extracted_fact_id IS NOT NULL AND source_verification_id IS NULL)
    OR (value_source = 'HUMAN' AND source_verification_id IS NOT NULL)
    OR (value_source = 'EXTERNAL' AND source_extracted_fact_id IS NULL AND source_verification_id IS NULL)
);

-- -----------------------------------------------------------------------------
-- Generic external entity links
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.entity_links (
    tenant_id                       varchar(128) NOT NULL,
    entity_link_id                  uuid NOT NULL,
    document_id                     uuid NOT NULL,
    source_system                   varchar(120) NOT NULL,
    entity_type                     varchar(120) NOT NULL,
    entity_id                       varchar(240) NOT NULL,
    link_status                     varchar(20) NOT NULL
                                      CHECK (link_status IN ('SUGGESTED','CONFIRMED','REJECTED','REMOVED')),
    link_confidence                 numeric(5,2)
                                      CHECK (link_confidence IS NULL OR (link_confidence >= 0 AND link_confidence <= 100)),
    match_reasons                   jsonb,
    link_method                     varchar(40) NOT NULL
                                      CHECK (link_method IN ('CALLER','SYSTEM','HUMAN')),
    linked_by_actor_id              varchar(160) NOT NULL,
    linked_at_utc                   timestamptz NOT NULL,
    removed_at_utc                  timestamptz,
    PRIMARY KEY (tenant_id, entity_link_id),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id),
    FOREIGN KEY (tenant_id, linked_by_actor_id) REFERENCES docintel.actors(tenant_id, actor_id)
);

CREATE INDEX ix_entity_link_external
ON docintel.entity_links(tenant_id, source_system, entity_type, entity_id)
WHERE link_status IN ('SUGGESTED','CONFIRMED');

-- -----------------------------------------------------------------------------
-- WhatsApp routes / intake / system quarantine
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.whatsapp_routes (
    route_id                         uuid PRIMARY KEY,
    destination_ref                 varchar(500) NOT NULL UNIQUE,
    tenant_id                       varchar(128) NOT NULL,
    system_actor_id                 varchar(160) NOT NULL,
    system_actor_type               varchar(20) NOT NULL DEFAULT 'SYSTEM' CHECK (system_actor_type = 'SYSTEM'),
    status                          varchar(20) NOT NULL DEFAULT 'ACTIVE'
                                      CHECK (status IN ('ACTIVE','INACTIVE')),
    created_at_utc                  timestamptz NOT NULL,
    updated_at_utc                  timestamptz NOT NULL,
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id),
    FOREIGN KEY (tenant_id, system_actor_id, system_actor_type) REFERENCES docintel.actors(tenant_id, actor_id, actor_type)
);

CREATE TABLE docintel.integration_intake_events (
    tenant_id                       varchar(128) NOT NULL,
    intake_event_id                 uuid NOT NULL,
    correlation_id                  varchar(128) NOT NULL,
    source_channel                  varchar(20) NOT NULL CHECK (source_channel = 'WHATSAPP'),
    source_event_id                 varchar(300) NOT NULL,
    source_sender_ref               varchar(500),
    source_destination_ref          varchar(500),
    source_media_ref                varchar(500),
    source_event_at                 timestamptz,
    message_text                    text,
    document_id                     uuid,
    status                          varchar(20) NOT NULL
                                      CHECK (status IN ('RECEIVED','DOCUMENT_CREATED','DUPLICATE','FAILED')),
    received_at_utc                 timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, intake_event_id),
    UNIQUE (tenant_id, source_event_id),
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id),
    FOREIGN KEY (tenant_id, document_id) REFERENCES docintel.documents(tenant_id, document_id)
);

-- System-level quarantine exists because Tenant is not yet known; it is not exposed through tenant RLS APIs.
CREATE TABLE docintel.system_intake_quarantine (
    quarantine_id                   uuid PRIMARY KEY,
    correlation_id                  varchar(128) NOT NULL,
    source_channel                  varchar(20) NOT NULL CHECK (source_channel = 'WHATSAPP'),
    source_event_id                 varchar(300) NOT NULL UNIQUE,
    source_sender_ref               varchar(500),
    source_destination_ref          varchar(500),
    source_media_ref                varchar(500),
    source_event_at                 timestamptz,
    temporary_storage_id            uuid,
    temporary_logical_object_key    varchar(1000),
    file_size_bytes                 bigint CHECK (file_size_bytes IS NULL OR file_size_bytes >= 0),
    content_hash_sha256             char(64),
    reason_code                     varchar(120) NOT NULL,
    status                          varchar(20) NOT NULL DEFAULT 'OPEN'
                                      CHECK (status IN ('OPEN','RESOLVED','DISCARDED')),
    received_at_utc                 timestamptz NOT NULL,
    resolved_at_utc                 timestamptz
);

-- -----------------------------------------------------------------------------
-- Idempotency
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.idempotency_records (
    tenant_id                       varchar(128) NOT NULL,
    idempotency_record_id           uuid NOT NULL,
    actor_id                        varchar(160) NOT NULL,
    operation_key                   varchar(160) NOT NULL,
    idempotency_key                 varchar(240) NOT NULL,
    request_hash                    char(64) NOT NULL,
    response_status                 integer,
    response_body                   jsonb,
    created_at_utc                  timestamptz NOT NULL,
    expires_at_utc                  timestamptz NOT NULL,
    PRIMARY KEY (tenant_id, idempotency_record_id),
    UNIQUE (tenant_id, actor_id, operation_key, idempotency_key),
    FOREIGN KEY (tenant_id, actor_id) REFERENCES docintel.actors(tenant_id, actor_id)
);

-- -----------------------------------------------------------------------------
-- Append-only tamper-evident audit log
-- -----------------------------------------------------------------------------
CREATE TABLE docintel.audit_chain_heads (
    tenant_id                       varchar(128) PRIMARY KEY,
    last_event_hash                 char(64),
    last_event_at_utc               timestamptz,
    FOREIGN KEY (tenant_id) REFERENCES docintel.tenant_settings(tenant_id)
);

CREATE TABLE docintel.system_audit_chain_head (
    singleton_key                   boolean PRIMARY KEY DEFAULT true CHECK (singleton_key),
    last_event_hash                 char(64),
    last_event_at_utc               timestamptz
);

INSERT INTO docintel.system_audit_chain_head(singleton_key) VALUES (true) ON CONFLICT DO NOTHING;

CREATE TABLE docintel.system_audit_events (
    system_audit_event_id           uuid PRIMARY KEY,
    actor_type                      varchar(20) NOT NULL
                                      CHECK (actor_type IN ('SYSTEM','SERVICE','USER')),
    actor_id                        varchar(160) NOT NULL,
    event_type                      varchar(160) NOT NULL,
    entity_type                     varchar(80) NOT NULL,
    entity_id                       varchar(240) NOT NULL,
    occurred_at_utc                 timestamptz NOT NULL,
    correlation_id                  varchar(128),
    before_state                    jsonb,
    after_state                     jsonb,
    metadata                        jsonb,
    previous_event_hash             char(64),
    event_hash                      char(64) NOT NULL UNIQUE
);

CREATE TABLE docintel.audit_events (
    tenant_id                       varchar(128) NOT NULL,
    audit_event_id                  uuid NOT NULL,
    actor_type                      varchar(20) NOT NULL
                                      CHECK (actor_type IN ('USER','SYSTEM','SERVICE')),
    actor_id                        varchar(160) NOT NULL,
    event_type                      varchar(160) NOT NULL,
    entity_type                     varchar(80) NOT NULL,
    entity_id                       varchar(240) NOT NULL,
    occurred_at_utc                 timestamptz NOT NULL,
    correlation_id                  varchar(128),
    before_state                    jsonb,
    after_state                     jsonb,
    metadata                        jsonb,
    previous_event_hash             char(64),
    event_hash                      char(64) NOT NULL,
    PRIMARY KEY (tenant_id, audit_event_id),
    UNIQUE (tenant_id, event_hash),
    FOREIGN KEY (tenant_id, actor_id) REFERENCES docintel.actors(tenant_id, actor_id)
);

CREATE INDEX ix_audit_entity
ON docintel.audit_events(tenant_id, entity_type, entity_id, occurred_at_utc DESC);

-- -----------------------------------------------------------------------------
-- Immutability controls
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION docintel.reject_update_delete()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    RAISE EXCEPTION 'immutable row: % mutation is not allowed on %.%', TG_OP, TG_TABLE_SCHEMA, TG_TABLE_NAME;
END;
$$;

CREATE TRIGGER audit_events_immutable
BEFORE UPDATE OR DELETE ON docintel.audit_events
FOR EACH ROW EXECUTE FUNCTION docintel.reject_update_delete();

CREATE TRIGGER system_audit_events_immutable
BEFORE UPDATE OR DELETE ON docintel.system_audit_events
FOR EACH ROW EXECUTE FUNCTION docintel.reject_update_delete();

CREATE OR REPLACE FUNCTION docintel.guard_extraction_profile_header()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'published/retired extraction profile cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.status = 'RETIRED' THEN
        RAISE EXCEPTION 'retired extraction profile is immutable';
    END IF;
    IF OLD.status = 'PUBLISHED' THEN
        IF NEW.status <> 'RETIRED'
           OR NEW.profile_id IS DISTINCT FROM OLD.profile_id
           OR NEW.document_type_id IS DISTINCT FROM OLD.document_type_id
           OR NEW.scope_tenant_id IS DISTINCT FROM OLD.scope_tenant_id
           OR NEW.version_no IS DISTINCT FROM OLD.version_no
           OR NEW.profile_name IS DISTINCT FROM OLD.profile_name
           OR NEW.classification_hint IS DISTINCT FROM OLD.classification_hint
           OR NEW.created_by_actor_id IS DISTINCT FROM OLD.created_by_actor_id
           OR NEW.published_by_actor_id IS DISTINCT FROM OLD.published_by_actor_id
           OR NEW.created_at_utc IS DISTINCT FROM OLD.created_at_utc
           OR NEW.published_at_utc IS DISTINCT FROM OLD.published_at_utc
        THEN
            RAISE EXCEPTION 'published extraction profile content is immutable; only retirement during atomic supersession is allowed';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER extraction_profile_header_guard
BEFORE UPDATE OR DELETE ON docintel.extraction_profiles
FOR EACH ROW EXECUTE FUNCTION docintel.guard_extraction_profile_header();

CREATE OR REPLACE FUNCTION docintel.guard_extraction_profile_child()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    p_id uuid;
    p_status varchar(20);
BEGIN
    IF TG_TABLE_NAME = 'extraction_profile_fields' THEN
        p_id := COALESCE(NEW.profile_id, OLD.profile_id);
    ELSE
        SELECT profile_id INTO p_id
        FROM docintel.extraction_profile_fields
        WHERE profile_field_id = COALESCE(NEW.profile_field_id, OLD.profile_field_id);
    END IF;
    SELECT status INTO p_status FROM docintel.extraction_profiles WHERE profile_id = p_id;
    IF p_status IS DISTINCT FROM 'DRAFT' THEN
        RAISE EXCEPTION 'published/retired extraction profile children are immutable';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER extraction_profile_fields_guard
BEFORE INSERT OR UPDATE OR DELETE ON docintel.extraction_profile_fields
FOR EACH ROW EXECUTE FUNCTION docintel.guard_extraction_profile_child();
CREATE TRIGGER profile_field_normalizers_guard
BEFORE INSERT OR UPDATE OR DELETE ON docintel.profile_field_normalizers
FOR EACH ROW EXECUTE FUNCTION docintel.guard_extraction_profile_child();
CREATE TRIGGER profile_field_validators_guard
BEFORE INSERT OR UPDATE OR DELETE ON docintel.profile_field_validators
FOR EACH ROW EXECUTE FUNCTION docintel.guard_extraction_profile_child();

CREATE OR REPLACE FUNCTION docintel.guard_requirement_profile_header()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF TG_OP = 'DELETE' THEN
        IF OLD.status <> 'DRAFT' THEN
            RAISE EXCEPTION 'published/retired requirement profile cannot be deleted';
        END IF;
        RETURN OLD;
    END IF;
    IF OLD.status = 'RETIRED' THEN
        RAISE EXCEPTION 'retired requirement profile is immutable';
    END IF;
    IF OLD.status = 'PUBLISHED' THEN
        IF NEW.status <> 'RETIRED'
           OR NEW.tenant_id IS DISTINCT FROM OLD.tenant_id
           OR NEW.requirement_profile_id IS DISTINCT FROM OLD.requirement_profile_id
           OR NEW.profile_key IS DISTINCT FROM OLD.profile_key
           OR NEW.version_no IS DISTINCT FROM OLD.version_no
           OR NEW.description IS DISTINCT FROM OLD.description
           OR NEW.created_by_actor_id IS DISTINCT FROM OLD.created_by_actor_id
           OR NEW.published_by_actor_id IS DISTINCT FROM OLD.published_by_actor_id
           OR NEW.created_at_utc IS DISTINCT FROM OLD.created_at_utc
           OR NEW.published_at_utc IS DISTINCT FROM OLD.published_at_utc
        THEN
            RAISE EXCEPTION 'published requirement profile content is immutable; only retirement during atomic supersession is allowed';
        END IF;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER requirement_profile_header_guard
BEFORE UPDATE OR DELETE ON docintel.document_requirement_profiles
FOR EACH ROW EXECUTE FUNCTION docintel.guard_requirement_profile_header();

CREATE OR REPLACE FUNCTION docintel.guard_requirement_profile_item()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
    p_tenant varchar(128);
    p_id uuid;
    p_status varchar(20);
BEGIN
    p_tenant := COALESCE(NEW.tenant_id, OLD.tenant_id);
    p_id := COALESCE(NEW.requirement_profile_id, OLD.requirement_profile_id);
    SELECT status INTO p_status
    FROM docintel.document_requirement_profiles
    WHERE tenant_id = p_tenant AND requirement_profile_id = p_id;
    IF p_status IS DISTINCT FROM 'DRAFT' THEN
        RAISE EXCEPTION 'published/retired requirement profile items are immutable';
    END IF;
    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER requirement_profile_items_guard
BEFORE INSERT OR UPDATE OR DELETE ON docintel.document_requirement_profile_items
FOR EACH ROW EXECUTE FUNCTION docintel.guard_requirement_profile_item();

-- -----------------------------------------------------------------------------
-- RLS: tenant-owned transactional/configuration tables
-- Application must SET LOCAL app.tenant_id = '<authorized tenant>' in each transaction.
-- -----------------------------------------------------------------------------
DO $$
DECLARE
    t text;
BEGIN
    FOREACH t IN ARRAY ARRAY[
        'tenant_settings','actors','registered_devices','retention_policies',
        'document_requirement_profiles','document_requirement_profile_items','subject_requirement_assignments',
        'subjects','subject_identifiers','channel_identities','documents','document_artifacts','document_quality_results','processing_jobs',
        'processing_runs','processor_invocations','document_classifications','extracted_facts',
        'document_field_values','validation_results','human_verifications','entity_links',
        'integration_intake_events','idempotency_records','audit_chain_heads','audit_events'
    ]
    LOOP
        EXECUTE format('ALTER TABLE docintel.%I ENABLE ROW LEVEL SECURITY', t);
        EXECUTE format(
            'CREATE POLICY tenant_isolation ON docintel.%I USING (tenant_id = docintel.current_tenant_id()) WITH CHECK (tenant_id = docintel.current_tenant_id())',
            t
        );
    END LOOP;
END $$;

-- Global/default configuration tables use owner/scope tenant columns rather than tenant_id.
ALTER TABLE docintel.document_types ENABLE ROW LEVEL SECURITY;
CREATE POLICY document_types_read_scope ON docintel.document_types
USING (owner_tenant_id IS NULL OR owner_tenant_id = docintel.current_tenant_id())
WITH CHECK (owner_tenant_id = docintel.current_tenant_id());

ALTER TABLE docintel.canonical_fields ENABLE ROW LEVEL SECURITY;
CREATE POLICY canonical_fields_read_scope ON docintel.canonical_fields
USING (owner_tenant_id IS NULL OR owner_tenant_id = docintel.current_tenant_id())
WITH CHECK (owner_tenant_id = docintel.current_tenant_id());

ALTER TABLE docintel.extraction_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY extraction_profiles_read_scope ON docintel.extraction_profiles
USING (scope_tenant_id IS NULL OR scope_tenant_id = docintel.current_tenant_id())
WITH CHECK (scope_tenant_id = docintel.current_tenant_id());

-- extraction_profile_fields/normalizers/validators are authorized through their parent profile by the service layer.
ALTER TABLE docintel.extraction_profile_fields ENABLE ROW LEVEL SECURITY;
CREATE POLICY extraction_profile_fields_scope ON docintel.extraction_profile_fields
USING (
    EXISTS (
        SELECT 1 FROM docintel.extraction_profiles p
        WHERE p.profile_id = extraction_profile_fields.profile_id
          AND (p.scope_tenant_id IS NULL OR p.scope_tenant_id = docintel.current_tenant_id())
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1 FROM docintel.extraction_profiles p
        WHERE p.profile_id = extraction_profile_fields.profile_id
          AND p.scope_tenant_id = docintel.current_tenant_id()
    )
);

ALTER TABLE docintel.profile_field_normalizers ENABLE ROW LEVEL SECURITY;
CREATE POLICY profile_field_normalizers_scope ON docintel.profile_field_normalizers
USING (
    EXISTS (
        SELECT 1
        FROM docintel.extraction_profile_fields f
        JOIN docintel.extraction_profiles p ON p.profile_id = f.profile_id
        WHERE f.profile_field_id = profile_field_normalizers.profile_field_id
          AND (p.scope_tenant_id IS NULL OR p.scope_tenant_id = docintel.current_tenant_id())
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM docintel.extraction_profile_fields f
        JOIN docintel.extraction_profiles p ON p.profile_id = f.profile_id
        WHERE f.profile_field_id = profile_field_normalizers.profile_field_id
          AND p.scope_tenant_id = docintel.current_tenant_id()
    )
);

ALTER TABLE docintel.profile_field_validators ENABLE ROW LEVEL SECURITY;
CREATE POLICY profile_field_validators_scope ON docintel.profile_field_validators
USING (
    EXISTS (
        SELECT 1
        FROM docintel.extraction_profile_fields f
        JOIN docintel.extraction_profiles p ON p.profile_id = f.profile_id
        WHERE f.profile_field_id = profile_field_validators.profile_field_id
          AND (p.scope_tenant_id IS NULL OR p.scope_tenant_id = docintel.current_tenant_id())
    )
)
WITH CHECK (
    EXISTS (
        SELECT 1
        FROM docintel.extraction_profile_fields f
        JOIN docintel.extraction_profiles p ON p.profile_id = f.profile_id
        WHERE f.profile_field_id = profile_field_validators.profile_field_id
          AND p.scope_tenant_id = docintel.current_tenant_id()
    )
);

-- Global normalization/validation/quality rule catalogs are read-only to normal tenant application roles; write privilege is reserved for platform administration.

COMMIT;
